services:
  frontend:
    image: lumilukko/lector:latest
    container_name: booklegion-lector
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      # Frontend router: everything except /api
      - "traefik.http.routers.booklegion-frontend.rule=Host(`book.lumilukko.com`)"
      - "traefik.http.routers.booklegion-frontend.entrypoints=websecure"
      - "traefik.http.routers.booklegion-frontend.tls=true"
      - "traefik.http.routers.booklegion-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.booklegion-frontend.loadbalancer.server.port=80"

    networks:
      - web
    restart: unless-stopped

  tribune_dictio:
    image: lumilukko/tribune_dictio
    container_name: booklegion-tribune_dictio
    environment:
      - DEBUG=true
    ports:
      - 8888:8000
    volumes:
      - /mnt/private/Serversetup/data/audio:/voiceactors
    devices:
      - nvidia.com/gpu=all
    restart: unless-stopped
    networks:
      - web

  onboarder:
    image: lumilukko/tribune_archivum:latest
    container_name: booklegion-tribune_archivum
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HARDCOVER_API_ENDPOINT=https://api.hardcover.app/v1/graphql
      - TRIBUNE_LOGISTICA_URL=http://booklegion-tribune_logistica:8000
      - RUST_LOG=debug
    volumes:
      - /mnt/private/Serversetup/data/booklegion:/data
      - /mnt/private/booklegion-onboard:/onboard
      - /mnt/private/booklegion-onboard-errors:/errs
    networks:
      - web

  backend:
    image: lumilukko/tribune_logistica:latest
    container_name: booklegion-tribune_logistica
    depends_on:
      - tribune_dictio
    environment:
      - TTS_BACKEND=http
      - LIBRARY_ROOT=/data
      - TTS_API_URL=http://booklegion-tribune_dictio:8000/tts
    env_file:
      - .env
    volumes:
      - /mnt/private/Serversetup/data/booklegion:/data
      - /mnt/private/Serversetup/configs/booklegion:/config
      - /mnt/private/onboard-staging:/onboard
      - /mnt/private/onboard-staging-errors:/errs
    labels:
      - "traefik.enable=true"
      # Router for backend
      - "traefik.http.routers.staging-backend.rule=Host(`book.lumilukko.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.staging-backend.entrypoints=websecure"
      - "traefik.http.routers.staging-backend.tls=true"
      - "traefik.http.routers.staging-backend.tls.certresolver=letsencrypt"
      # Service port inside container
      - "traefik.http.services.staging-backend.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
