services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=super_secret_password
      - DUPLICATI__WEBSERVICE_PASSWORD=My_Duplicati
      - DUPLICATI__DISABLE_DB_ENCRYPTION=false
    volumes:
      - /mnt/private/Serversetup/configs/duplicati:/config
      - /mnt/private/Serversetup/data:/source
      - /mnt/router/serverbackups:/backups
    ports:
      - 8200:8200
    restart: unless-stopped