services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://vault.lumilukonservu.duckdns.org"
    ports:
      - "7000:80"
    restart: unless-stopped
    volumes:
      - /home/pete/servu/data/vaultwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.lumilukonservu.duckdns.org`)"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      
      # Websocket support
      # - "traefik.http.middlewares.vw-websocket.headers.customrequestheaders.Connection=upgrade"
      # - "traefik.http.middlewares.vw-websocket.headers.customrequestheaders.Upgrade=websocket"
      # - "traefik.http.routers.vaultwarden.middlewares=vw-websocket"
    networks:
      - web


networks:
  web:
    external: true